In [9]:
import numpy

linear algebra module,  linear equation system $\mathbf{Ax} = \mathbf{b}$ unique solution

In [6]:
# b is the target vector
# If A is a square matrix, n of b cannot be less than n of A
def problem1(A, b):
    shapeofA = A.shape
    shapeofB = b.shape
    if (shapeofA[0] == shapeofA[1]) and (shapeofA[0] == shapeofB[0]) and (numpy.linalg.det(A) != 0):
# or if (shapeofA[0] == shapeofA[1]) and (shapeofA[1] == shapeofB[0]) and (numpy.linalg.det(A) != 0):
        return True
    else:
        return False

linear algebra module that returns the elapsed time (seconds) required to solve the linear equation system $\mathbf{Ax} = \mathbf{b}$ using Gaussian Elimination or the inverse method

In [7]:
import time
def problem2(A, b, method):
    solveable = problem1(A, b)
    if solveable == True:
        if method == "ge":
            numpy.linalg.solve(A, b)
            return time.perf_counter()
        if method == "inv":
            inverseofmatrix = numpy.linalg.inv(A)
            numpy.linalg.solve(inverseofmatrix, b)
            return time.perf_counter()
    else:
        return None

polyfit() returns a `array` of the coefficients of the best-fit polynomial $t(n)$ for the runtime of Gaussian elimination or the inverse matrix method

$t(n) = a_0 + a_1 n + a_2 n^2 + a_3 n^3$

where $t(n)$ is the runtime of the method for solving a linear system of size $n$. The input argument `n_array` specifies the dimensions of the linear systems that should be used as a sample set to measure runtimes which are then used to determine a best-fit. The best fit $t(n)$ provides us with an approximation of the runtime versus linear system size for the specified method (`"ge"` or `"inv"`).

The `random.random()` function should be used to generate the linear equation systems of different dimensions (specified by `n_array`) which, in turn, will be used to create timing data points $(n, t)$ for fitting to the polynomial.

In [10]:
def problem3(n_array, method):
    
    #n_array is an array of numbers that will tell us what size each matrix that we want to make is
    #size is to tell us the number of matrices we are making
    
    time_array = numpy.zeros(n_array.shape[0])
    #we are making an empty array of zeros with first index of the shape, which is the number of columns in a 1 dimensional array

    x = 0
    #0 is the starting value

    for n in n_array:
        
        #n by n is a square matrix
        A = numpy.random.random((n, n))
        b = numpy.random.random((n, 1))
        time_array[x] = problem2(A, b, method)
        #calculates the running time
        x += 1
        #adds an array each time

    return numpy.polyfit(n_array, time_array, 3)
    #n_array is x, time_array is y, and 3 is the degree
print(problem3(3, "ge"))

AttributeError: 'int' object has no attribute 'shape'

In [11]:
n_array = numpy.array([1, 2, 4, 3])
time_array = numpy.array(numpy.zeros(n_array.shape[0]))
time_array2 = numpy.empty(n_array.shape[0])
time_array3 = numpy.zeros(4)
print(time_array)
print(time_array2)
print(time_array3)
print(n_array.shape[0])
print(n_array.shape)

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
4
(4,)


In [12]:
A = [1, 2, 3]
def solution(A):
    
    sortedarray = sorted(A)
    print(sortedarray)
    for eachint in sortedarray:
        counter = 1
        print(eachint)
        if eachint != counter:
            smallest = counter
        else:
            counter += 1
    
    return smallest
print(solution(A))

[1, 2, 3]
1
2
3
1
