# Exercise 8

In [14]:
# Execute this code block to import the NumPy library
import numpy

#### Problem 1

Create an `ndarray` object with data-type `float`, shape (2,3,4), and all values initialized to `5`.

In [15]:
problem1 = numpy.ones([2,3,4], dtype = float)* 5

[[[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]

 [[5. 5. 5. 5.]
  [5. 5. 5. 5.]
  [5. 5. 5. 5.]]]


#### Problem 2

Develop a function `problem2(array1, array2)` with returns `True` if binary arithmetic operations (+, -, \*, etc) may be applied to the arrays `array1` and `array2`, `False` otherwise.

In [24]:
def problem2(array1, array2):
    try:
        add = array1 + array2
        mult = array1 * array2
        minus = array1 - array2
    except:
        return False
    return True

True


#### Problem 3

Develop a function `problem3(array1, array2)` that returns the shape of the result of applying binary arithmetic operations (+, -, \*, etc) to the arrays `array1` and `array2` or `None` if doing so would result in a semantic error.

In [29]:
def problem3(array1, array2):
    try:
        add = array1 + array2
        mult = array1 * 2
        minus = array1 - array2
        return array1.shape
    except:
        return None


#### Problem 4

Given an array `p4arr`, create a new array whose values correspond to applying the natural logarithm to each of the values in `p4arr`.

In [33]:
problem4 = numpy.log(p4arr)

[1.60943791 1.09861229 1.79175947]


#### Problem 5

Create an `ndarray` with values ranging from 5 to 50 in increments of 5.

In [5]:
problem5 = numpy.arange(5, 51, 5)

[ 5 10 15 20 25 30 35 40 45 50]


#### Problem 6

Create an `ndarray` with values ranging from 5 to 50 in increments of 5 in a way different from the previous problem.

In [34]:
problem6 = numpy.arange(5., 51, 5)

#### Problem 7

Develop a function `problem7(array1)` which returns a tuple `(min, max, mean)` of the minimum, maximum, and mean values in the array.

In [38]:
array1 = ([4, 7, 7])
def problem7(array1):
    minimum = array1.min()
    maximum = array1.max()
    meann = array1.mean()
    return minimum, maximum, meann

#### Problem 8

Given an array of integers `p8arr`, determine the number of values in the array greater than 5 **without** using loops.

In [28]:
problem8 = numpy.count_nonzero(p8arr >5)

NameError: name 'p8arr' is not defined